service: kvo-auction-service # define meta-data of service
#app: your-app-name
#org: your-org-name

plugins: #
  - serverless-bundle # plugin that optimally packages your ES6 or TypeScript Node.js Lambda functions
  - serverless-pseudo-parameters # use the CloudFormation Pseudo Parameters in your serverless.yml

provider:
  name: aws # cloud provider
  runtime: nodejs14.x # runtime programming language
  lambdaHashingVersion: 20201221
  region: ap-southeast-2 # default region
  stage: ${opt:stage, 'sit'} # environment state

functions:
  healthcheck:
    handler: auction/healthcheck.handler
    events:
      - http:
          method: 'GET'
          path: /${self:custom.apiVersion}/healthcheck
  createAuction:
    handler: auction/createAuction.handler
    events:
      - http:
          method: 'POST'
          path: /${self:custom.apiVersion}/auction
  # getAuctions:
  #   handler: auction/getAuctions.handler 
  #   events:
  #     - http:
  #         method: GET
  #         path: /${self:custom.apiVersion}/auctions
  #         authorizer: ${self:custom.authorizer}
  # getAuction:
  #   handler: auction/getAuction.handler 
  #   events:
  #     - http:
  #         method: GET
  #         path: /${self:custom.apiVersion}/auction/{id}
  #         authorizer: ${self:custom.authorizer}
  # placeBid:
  #   handler: auction/placeBid.handler 
  #   events:
  #     - http:
  #         method: PATCH # don't use POST because it uses for creation. Patch is update a property of a auction
  #         path: /${self:custom.apiVersion}/auction/{id}/bid
  #         authorizer: ${self:custom.authorizer}
  processAuctions:
    handler: auction/processAuctions.handler 
    # events:
    #   - schedule: rate(1 minute) # it similiars cron job
custom:
  authorizer: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:auth-service-${self:provider.stage}-auth
  AuctionsTable:
    name: !Ref AuctionsTable
    arn: !GetAtt AuctionsTable.Arn
  bundle:
    linting: false
  apiVersion: v1
