service: kvo-auction-service #define meta-data of service
#app: your-app-name
#org: your-org-name

plugins: #
  - serverless-bundle #plugin that optimally packages your ES6 or TypeScript Node.js Lambda functions
  - serverless-pseudo-parameters #use the CloudFormation Pseudo Parameters in your serverless.yml

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: ap-southeast-2
  stage: ${opt:stage, 'sit'}

functions:
  healthcheck:
    handler: src/utility/healthcheck.handler
    events:
      - http:
          method: 'GET'
          path: /${self:custom.apiVersion}/healthcheck
custom:
  linting: false
  apiVersion: v1
